version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./site:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: vgubusdb
    ports:
      - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
